### ISSUE TITLE
DatabaseMetaData's getTables didn't return the data

### ISSUE THREAD

**Issue by WillWei1983** [apache/incubator-shardingsphere#1741]
my app connect to the sharding-prox with bitronix jdbc driver. when my app try to check if the tables existed before doing other operations. I use the DatabaseMetaData.getTables to do it ,I have handled the case sensitive, but it always return no record. but in fact ,the table existed.

**Comment by tuohai666** [comment]
Please **DO** fill in the bug report template.

## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by WillWei1983** [comment]
**Which version of ShardingSphere did you use?**
3.0.0
**Which project did you use? Sharding-JDBC or Sharding-Proxy?**
Sharding-Proxy
**Expected behavior**
Return the description of the tables
**Actual behavior**
Return nothing
**Reason analyze (If you can)**
I guess the Sharding-Proxy did not support this yet

Steps to reproduce the behavior,Example Code

> con = efi.getConnection(groupName)
                DatabaseMetaData dbData = con.getMetaData()

                String[] types = ["TABLE", "VIEW", "ALIAS", "SYNONYM"]
                tableSet1 = dbData.getTables(null, ed.getSchemaName(), ed.getTableName(), types)
                if (tableSet1.next()) {
                    dbResult = true
                } else {
                    // try lower case, just in case DB is case sensitive
                    tableSet2 = dbData.getTables(null, ed.getSchemaName(), ed.getTableName().toLowerCase(), types)
                    if (tableSet2.next()) {
                        dbResult = true
                    } else {
                        if (logger.isTraceEnabled()) logger.trace("Table for entity ${ed.getFullEntityName()} does NOT exist")
                        dbResult = false
                    }
                }

**Comment by tuohai666** [comment]
I'll check later.

**Comment by tuohai666** [comment]
@WillWei1983 I can't reproduced. Here's my SQL:
ResultSet resultSet = databaseMetaData.getTables(null, "%", "%", null);
You may try SQL like mine. Or,
show me the schemaName and tableName parameter, **and** schemaName/tableName in your **logical database.**

**Comment by tuohai666** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
