### ISSUE TITLE
exception will thrown if sql contains use index(index_name) in mysql

### ISSUE THREAD

**Issue by jmbkeyes** [apache/incubator-shardingsphere#1783]
I'm using sharding-jdbc 3.0.0.
There's a complicated sql statements, and some big tables have several indexes, mysql will chose a better index according to its evalutation. But it'll not a best index, so we add use index statement to force mysql to use the index.
[bug details]
exception will be thrown if sql contains use index(index_name) in mysql.

2019-01-18 19:06:45 ERROR errorLogger:40 - Cannot find logic table name with logic index name: 'uk_e9fmb4uxwkpopbbfdbdleuj82'

**Comment by terrymanu** [comment]
Hi, can you provide information we needed as below?

**Comment by terrymanu** [comment]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by jmbkeyes** [comment]
I've added more details.

**Comment by jmbkeyes** [comment]
hmm, I said that the exception occurred in 3.0.0.   3.1.0 has another issue [https://github.com/apache/incubator-shardingsphere/issues/1774](issue), so I tried 3.0.0, and find this issue.

**Comment by terrymanu** [comment]
So can I label this issue duplicated with #1774?

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
