### ISSUE TITLE
when the Logic SQL is very long, SQLLogger print too much. if the Logic SQL is Cross-sharding，that's worse

### ISSUE THREAD

**Issue by feelwing1314** [apache/incubator-shardingsphere#1818]
## Feature Request

when the Logic SQL is very long, SQLLogger print too much. if the Logic SQL is Cross-sharding，that's worse：
if there are 128 sharding table，there are 128 Actual SQL .
and SQLStatement and Logic SQL also will Output thousands of lines .

These outputs are of little value. So suggest that add a configuration(for example: **sharding.jdbc.config.props.sql.show.simple=true**) to simple it.

**Comment by terrymanu** [comment]
Cloud you submit a pull request

**Comment by betterjava** [comment]
I am to  glad to add  this feature ,but which mentor can  help me to discuss the design of this ?  I am new to the opensource....

**Comment by terrymanu** [comment]
@betterjava Welcome to contribute code. you you can read contributor guide first: https://shardingsphere.apache.org/community/en/contribute/contributor/, hope to help you.

**Comment by betterjava** [comment]
I have read it some days ago. Furthermore I have pull a request  to add the future.But I close the pull due to it let test coverage decrease. [#2074](https://github.com/apache/incubator-shardingsphere/pull/2074). I added a integer properties (not boolean) to log config , and I do not know whether it is suitable or not ..
