### ISSUE TITLE
4.0.0.M1-SNAPSHOT report a error :  current logic schema is null

### ISSUE THREAD

**Issue by guowdxp** [apache/incubator-shardingsphere#1830]
The version using sharding-sphere is 4.0.0.M1-SNAPSHOT.
I use sharding-Proxy.
I configure a config-sharding file, there is no problem in querying data with java code, but I will get an error when connecting to the service with navicat.

     Unknown exception: current logic schema is null

**Comment by tuohai666** [comment]
@guowdxp Please explicit provide the SQL. And fill in the template below. Thanks.

## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).
