### ISSUE TITLE
make key-generator and encryptor strategy as a spring bean on spring namespace

### ISSUE THREAD

**Issue by cherrylzhao** [apache/incubator-shardingsphere#1977]
- [ ] key-generator
- [ ] encryptor strategy

**Comment by TaoZhiMLND** [comment]
I will try to solve it.

**Comment by terrymanu** [comment]
Thank you, assigned

**Comment by TaoZhiMLND** [comment]
When I looked at some code of sharding - core and sharding - spring, I found that ShardingDataSourceBeanDefinitionParser will register a SpringShardingDataSource bean to spring.Then according to the configuration in ShardingRuleConfiguration - > TableRuleConfiguration - > KeyGeneratorConfiguration, the constructor of SpringShardingDataSource creates the corresponding ShardingKeyGenerator instance by way of SPI.
When SPI is used to create an instance of a ShardingKeyGenerator, it will make all lot of peices instances of ShardingKeyGenerator of all types, and we can iterate to find type that we want. Now We can optimize this issue if we make the ShardingKeyGenerator as a spring bean, and at the time we need to considerate the decoupling of sharding-core and sharding-spring.
This is the context of this issue as I understand, am I right?

**Comment by terrymanu** [comment]
@TaoZhiMLND Sure, you are totally correct. We can discuss how to decouple it if you want.

**Comment by cherrylzhao** [comment]
it seems that we should instance KeyGenerator when constructing `KeyGeneratorConfiguration` instead of inside `TableRule`. for spring-namespace we can leverage `FactoryBean` to create KeyGenerator through our NewInstanceServiceLoader.

**Comment by TaoZhiMLND** [comment]
After the discussion with @cherrylzhao, we decide make key-generator as a spring bean on spring namespace in the following steps:

- [✓] change `shardingNamespace.xml` configuration.

- [✓] create class `KeyGeneratorFactoryBean` extends `TypeBasedSPIConfiguration`  implements `FactoryBean<ShardingKeyGenerator>`,leverage `FactoryBean` to create KeyGenerator.

- [✓] modify class `KeyGeneratorConfiguration`~~extends TypeBasedSPIConfiguration~~，add member variables `ShardingKeyGenerator keyGenerator`.

- [✓] modify class `KeyGeneratorBeanDefinitionParser` addConstructorArgReference with `KeyGenerator` by using TAG `generator-ref`.

- [✓] modify class `TableRule`, shardingKeyGenerator=tableRuleConfig.getKeyGeneratorConfig().getKeyGenerator().

- [✓] modify class `ShardingRule`, use keyGeneratorConfiguration.getKeyGenerator() instead of create by ShardingKeyGeneratorServiceLoader.

- [✓] modify correlative tests, add test on `ShardingKeyGenerator` Bean.

- [  ] modify docs and examples.

I'll commit a pr.
