### ISSUE TITLE
java.lang.NullPointerExceptionat io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:139)

### ISSUE THREAD

**Issue by zhubenle** [apache/incubator-shardingsphere#1989]
java.lang.NullPointerExceptionat io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:139)

Too little exception information

**Comment by terrymanu** [comment]
Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by lalalayyy** [comment]
1、exception:
![image](https://user-images.githubusercontent.com/45991555/127587426-8cfebd18-5267-4ae7-b49c-eb06c51c8611.png)
2、sharding-jdbc version
        <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>3.1.0</version>
        </dependency>
3、sql如1图中所示，只是一个简单的查询sql。
