### ISSUE TITLE
select * missing column

### ISSUE THREAD

**Issue by michaeljinxq** [apache/incubator-shardingsphere#2226]
(1)alter table my_orders add dc decimal(10,2);

(2)
show create table my_orders\G
create table my_orders (
id int(10) not null auto_increment,
name varchar(40) default null,
create_time datetime default null,
age int(11) default null,
ttt datetime(3) default null,
dc decimal(10,2) default null,
primary key (id)
)engine=innodb default charset=utf8;

(3)
insert into my_orders (name,create_time,age) values ('ruiaylin1','2019-04-16 18:00:00',15);

(4)dc column missing
select * from my_orders;
id     name         create_time         age     ttt     
1   ruiaylin1   2019-04-16 18:00:00      15     NULL

**Comment by tuohai666** [comment]
Root cause of this problem:
After ALTER clause of MySQL, sharding-proxy should refresh the metadata by JDBC for metadata changed by DDL clause. JDBC have to send SQLs to database to get the new metadata. But why metadata wasn't refreshed? 
I found cacheResultSetMetadata property of JDBC is setting by TRUE which make JDBC cache metadata but not access database to get a new one.
Set cacheResultSetMetadata = FALSE will fix this problem.
