### ISSUE TITLE
Oracle update update error

### ISSUE THREAD

**Issue by skywp** [apache/incubator-shardingsphere#2261]
## Question
When I used sharding-jdbc update oracle 11g databases,then something wrong.
* Error updating database.  Cause: java.sql.SQLException: ORA-01410 无效的 ROWID
Here is my pom.xml:
            `   
		<dependency>
		    <groupId>io.shardingsphere</groupId>
		    <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
		    <version>3.0.0</version>
		</dependency>
		<dependency>
		    <groupId>io.shardingsphere</groupId>
		    <artifactId>sharding-jdbc-spring-namespace</artifactId>
		    <version>3.0.0</version>
		</dependency>`

How can I fix it?

**Comment by terrymanu** [comment]
Can you provide necessary information? please reference by template

**Comment by skywp** [comment]
> Project use mybatis to connect the databases。
   Here is my mapper xml file.
<update id="updateBy" parameterType="api.entity.ActtrEntity">
        update <include refid="table"/>
        <set>
            CORP_BR_NO = #{corpBrNo,jdbcType=VARCHAR},
            OPN_BR_NO = #{opnBrNo,jdbcType=VARCHAR},
            AC_NO = #{acNo,jdbcType=VARCHAR},
            SPLIT_TABLE_KEY = #{splitTableKey,jdbcType=VARCHAR},
        </set>
        <where>
        	rowid = #{rowid,jdbcType=VARCHAR}
        </where>
    </update>

I wanna update data by using rowid,but something wrong.

**Comment by terrymanu** [comment]
Can you provide necessary information? please reference by template

template FYI:

## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
