### ISSUE TITLE
Reconstruct rewriting module

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#2275]
**Reconstruct rewriting module**
The tasks of parsing module:
- [x] Make all of the tokens store startIndex parameter and stopIndex parameter.
- [x] Remove the invalid parameters for calculating the stopIndex.
- [x] Add different interface to distinguish the SQLTokens for startIndex and stopIndex.

The tasks of rewriteEngine module:
- [x] Use startIndex and stopIndex to rewrite SQLs.
- [x] Make all of the tokens rewritten in the consistent method.
- [x] Generate placeHolders to handle ItemsToken, LimitRowCountToken and so on.
- [x] Delete getLogicTableName() from ShardingPlaceholder.
- [x] Move encrypting processing part to ShardingEncryptorEngine.
- [x] Use pattern() to create constant placeHolders, variant placeHolders, original literal from SQLTokens.
- [x] Add interface for variant placeHolders to toString(parameters).
- [x] Use pattern() to make constant placeHolders become literals, and create SQLBuilder to store placeHolder-literals, variant placeHolders and original literals.
- [x] Use generateSQL() to generate SQLUnit.

The tasks of SQLBuilder module:
- [x] Store variant placeHolders and placeHolder-literals and original literals.
- [x] Use toSQL() to generate SQLUnit.

**Comment by terrymanu** [comment]
Some code review suggestion:

1. XXXSQLRewriteEngine move to new package name as `engine`
2. XXXSQLRewriteEngine need implement a interface name as `SQLRewriteEngine`
3. MasterSlaveSQLRewriteEngine use @RequiredArgsConstructor
4. Constructor don't need java-doc
5. method of XXXSQLRewriteEngine.generateSQL is unnecessary, just call sqlBuilder.toSQL
6. Beside Alterable, add Addable interface
7. split sharding and encrypt placeholder in package `org.apache.shardingsphere.core.rewrite.placeholder`
8. EncryptXXXPlaceholder should not implement `ShardingPlaceholder`
9. Don't use @SuppressWarnings("all") on class EncryptUpdateItemColumnPlaceholder 
10. EncryptUpdateItemColumnPlaceholder has lots of field can be null, consider about the design, maybe split assistedColumn and not has assistedColumn situation
11. Question in EncryptWhereColumnPlaceholder, between should not supported
12. Should not call SQLUtil.getExactlyValue on rewrite module, current value should come from parse module. For example: IndexPlaceholder
13. Rewrite of class InsertSetPlaceholder is out of scope, should not rewrite "SET"

**Comment by terrymanu** [comment]
Some suggestions:

1. Remove SQLRewriteEngine.originalSQL, use sqlStatement.getLogicSQL()
2. For EncryptRule with SQLRewriteEngine, use current DatabaseType instead of DatabaseType.MySQL
3. SQLRewriteEngine.isRewriteDistinctLiteral => isMeedRewriteDistinctLiteral
4. SQLRewriteEngine.isContainsAggregationDistinctToken can move to sqlStatement, and let token type as an input parameter
5. SelectStatement.getFirstSelectItemStartIndex() should as a Token and Split append distinct from rewriteInitialLiteral
6. Make sure responsibility of rewriter and engine, only rewriter can use token
7. EncryptSQLRewriter & ShardingSQLRewriter can new instance out of loop
8. Make unify with stopPosition & stopIndex
9. sqlBuilder is global field with SQLRewriteEngine, may avoid pass from private method by input parameter
10. Make accurate with javadoc on SQLRewriter.rewrite
11. Avoid start a new line if not exceed 200 char one line, at line 107 on EncryptSQLRewriter
12. Make input parameter as same sequence for differnet methods, like: EncryptSQLRewriter.encryptInsertOptimizeResultUnit and EncryptSQLRewriter.encryptInsertOptimizeResult's param: unit
13. add Predicate if Optional can not be absent, at line 105 on EncryptSQLRewriter
14. InsertParameterUnit => InsertParameterGroup?

**Comment by tristaZero** [comment]
- [ ] Remove SQLRewriteEngine.originalSQL, use sqlStatement.getLogicSQL()
    - [ ] For EncryptRule with SQLRewriteEngine, use current DatabaseType instead of DatabaseType.MySQL
    - [ ] SQLRewriteEngine.isRewriteDistinctLiteral => isMeedRewriteDistinctLiteral
    - [ ] SQLRewriteEngine.isContainsAggregationDistinctToken can move to sqlStatement, and let token type as an input parameter
    - [ ] SelectStatement.getFirstSelectItemStartIndex() should as a Token and Split append distinct from rewriteInitialLiteral
    - [ ] Make sure responsibility of rewriter and engine, only rewriter can use token
    - [ ] EncryptSQLRewriter & ShardingSQLRewriter can new instance out of loop
    - [ ] Make unify with stopPosition & stopIndex
    - [ ] sqlBuilder is global field with SQLRewriteEngine, may avoid pass from private method by input parameter
    - [ ] Make accurate with javadoc on SQLRewriter.rewrite
    - [ ] Avoid start a new line if not exceed 200 char one line, at line 107 on EncryptSQLRewriter
    - [ ] Make input parameter as same sequence for differnet methods, like: EncryptSQLRewriter.encryptInsertOptimizeResultUnit - [ ] and EncryptSQLRewriter.encryptInsertOptimizeResult's param: unit
    - [ ] add Predicate if Optional can not be absent, at line 105 on EncryptSQLRewriter
    - [ ] InsertParameterUnit => InsertParameterGroup?
    - [ ] Decouple SQLBuilder & ParameterBuilder
    - [ ] Remove SchemaPlaceholder and test cases
    - [ ] Add new method appendPlaceholder for SQLToken and polymorphic appendXXXPlaceholder
