### ISSUE TITLE
How to execute ddl in specified DB by sharding-jdbc

### ISSUE THREAD

**Issue by xllove-moon** [apache/incubator-shardingsphere#2298]
I'm using sharding-jdbc to sharding tables by month and groupId,because the groupId are increasing，so  the table is dynamic
this is our table model:
          basetablename_month_groupId
For example 

ds0:basetablename_201902_01
      ......
      basetablename_201902_99

ds1:basetablename_201903_01
      ......
      basetablename_201903_99
      basetablename_201903_100

It means  ds0 not contains Data for March like basetablename_201903_100(because it is new),
but when i try to use "create table... like..." to ceate new table in my service ,ds0(In fact，all ds) also create one table.I try to debug source code and find how to solve it,but it shows no condition so it can not route  specified ds...
so....how to execute ddl in specified DB or there are other methods can help me to solve this?

**Comment by terrymanu** [comment]
Can not execute DDL if your sharding strategy is totally dynamic. DDL only can affect your current sharding strategy configuration.
Even using registry center can change sharding strategy configuration dynamically, but end-user still need to create table by themselves.
Use `CREATE TABLE IF NOT EXIST` is better if end-user change configuration via registry center.

**Comment by xllove-moon** [comment]
Thank you for your reply
I am changing my plan, i use another microService  to create new table instead of sharding-jdbc,and new table info will be sync to complex algorithm by microService,so algorithm can return right ds and table by shardingvalues

**Comment by MrZhangsun** [comment]
during sharding jdbc initialization, it will do three things:
1. load all exist tables from all ds;
2. calculate the actual-data-nodes by configured shard rule(list all actual table name, even it does't exist);
3. classify all tables to two types: sharding tables and single tables;
    3.1. the sharding tables are calculated by configured shard rule;
    3.2. the single tables are the intersection of the database tables and the sharding tables subtracted from the tables already existing in the database;

if you created a table dynamically, the sharding jdbc does't known which type it is. when you use the dynamic table, if you use the logic table name with sharding key, then sharding jdbc will calculate the actual data table name by logic table name and sharding key. if the calculated actual table name exists in "actual-data-nodes" and it exists in database, then you can use it correctly.

otherwise, you use it directly, that also, you use the actual data table name, sharding jdbc will route database by single table rule. when sharding jdbc can't find the table name from calculated single tables,  it will use the first datasource of configuration: "spring.shardingsphere.database.names: ds0, ds1, ds..."  as the default datasource, which we can't change it.

**Comment by MrZhangsun** [comment]
actually, you can try to create table by native jdbc rather than sharding jdbc. then you just neet to ensure the dynamic table in the list of "actual-data-nodes".
