### ISSUE TITLE
sharding-proxy 1046 - No database selected

### ISSUE THREAD

**Issue by gaochenfeng** [apache/incubator-shardingsphere#2345]
schemaName: sharding_db
dataSources:
 ds_0:
   url: jdbc:mysql://127.0.0.1:3306/eshop?serverTimezone=UTC&useSSL=false
   username: root
   password: 123456
   autoCommit: true
   connectionTimeout: 30000
   idleTimeout: 60000
   maxLifetime: 1800000
   maximumPoolSize: 50
shardingRule:
 tables:
   t_order:
     actualDataNodes: ds_0.t_order_${0..3}
     tableStrategy:
       inline:
         shardingColumn: order_id
         algorithmExpression: t_order_${order_id % 4}
     keyGeneratorColumnName: order_id   
 bindingTables:
   -t_order
 defaultDatabaseStrategy:
   none:
 defaultTableStrategy:
   none:
 defaultKeyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator

**Comment by terrymanu** [comment]
Can you provide more info like the template below?


## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by terrymanu** [comment]
I will close this issue soon if no response any more
