### ISSUE TITLE
shardingproxy 4.0.0-RC2：insert no field grammar execution error

### ISSUE THREAD

**Issue by 799983050** [apache/incubator-shardingsphere#2359]
`INSERT INTO `order_back_batch` VALUES (1125673913712640002, 1, '462c9d381e97491197cecca812e99831', 4.00, 1, 2, 80, '2019-05-07', '2019-05-07 16:09:09.696', '2019-05-07 16:09:11');`
`
![图片](https://user-images.githubusercontent.com/45658355/57431214-aa3e0c80-7264-11e9-8ace-d764ac651e6e.png)
Partitioning algorithm is customized
insert into  Add fields  Successful implementation

**Comment by cherrylzhao** [comment]
please tell us more details, proxy version? Sharding-rule configuration, and how can we reproduce it?

**Comment by terrymanu** [comment]
The title is too generic, Can you change the title to let it for search friendly?

**Comment by 799983050** [comment]
@cherrylzhao not Sharding-rule have nothing to do with.Remove and report errors.
insert into  Add fields  Successful implementation.You can try it out.
CREATE TABLE `order_back_batch`  (
  `id` bigint(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '主键',
  `order_type` tinyint(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '业务类型',
  `third_party_no` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '',
  `total_amount` decimal(18, 2) NOT NULL DEFAULT 0.00 COMMENT '',
  `total_count` int(11) NOT NULL DEFAULT 0 COMMENT '',
  `handling_time` int(11) NOT NULL DEFAULT 0 COMMENT '',
  `status_id` tinyint(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  `gmt_date` date NULL DEFAULT '0001-01-01' COMMENT '',
  `gmt_create` datetime(3) NOT NULL DEFAULT '0001-01-01 00:00:00.000' COMMENT '',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_order_type`(`order_type`) USING BTREE,
  INDEX `idx_third_party_no`(`third_party_no`) USING BTREE,
  INDEX `idx_status_id`(`status_id`) USING BTREE,
  INDEX `idx_gmt_create`(`gmt_create`) USING BTREE,
  INDEX `idx_gmt_date`(`gmt_date`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '' ROW_FORMAT = Dynamic;

**Comment by terrymanu** [comment]
Obviously, the title is mistake because not all insert SQL are caused error.
So can you change the title to let it for search friendly, not so generic?

**Comment by cherrylzhao** [comment]
it's so hard to understand what you mean...

**Comment by terrymanu** [comment]
Hi, can you follow template which can provide more necessary information to help us understand what's the issue you meet?

## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by terrymanu** [comment]
Closed by issue creator and cloud not provide necessary information, I just set the issue as invalid
