### ISSUE TITLE
sharding-jdbc TableMetaDataInitializer exception

### ISSUE THREAD

**Issue by duanbin0414** [apache/incubator-shardingsphere#2380]
Project start and TableMetaDataInitializer.getAllTableNames() loaded quartz Related tables and throw exception。
![1](https://user-images.githubusercontent.com/50389867/57675018-590e8e00-7653-11e9-8ea2-66854ce9b0ea.jpg)
![222](https://user-images.githubusercontent.com/50389867/57675037-61ff5f80-7653-11e9-832c-db43a61bec7c.jpg)
As shown, the prompt cannot find the table。

**Comment by terrymanu** [comment]
Can you fill necessary information which followed by template?  

## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by duanbin0414** [comment]
I use ShardingSphere4.0 and sharding-jdbc 4.0.0-RC1
 project start and loaded mysql's own tables that should not be loaded.

**Comment by cherrylzhao** [comment]
if you have configured default datasource, sharding-sphere will do this logic.

**Comment by terrymanu** [comment]
Can you show your sharding-rule configuration?

**Comment by duanbin0414** [comment]
> if you have configured default datasource, sharding-sphere will do this logic.

Thank you, that's right，but would there be any additional problems or overhead if you didn't configure the default data source

**Comment by duanbin0414** [comment]
> Can you show your sharding-rule configuration?

the Problems with configuring default data sources,I use internal encapsulation

**Comment by duanbin0414** [comment]
Found the reason, is my local database of individual reasons.
