### ISSUE TITLE
sharding-proxy fail to handle '0000-00-00 00:00:00' Timestamp result

### ISSUE THREAD

**Issue by liangcd** [apache/incubator-shardingsphere#2389]
Title:  sharding-proxy fail to handle '0000-00-00 00:00:00' Timestamp result

Env:  sharding-proxy-4.0.0-RC1

Problem:
mysql> mysql> * from tb_user_info limit 1;
ERROR: 
Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp

Other Info:
Create table sql:

CREATE TABLE `tb_user_info` (
  `USER_CODE` varchar(50) NOT NULL,
  `CREATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USER_NAME` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`USER_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by tuohai666** [comment]
I can't reproduce:
![image](https://user-images.githubusercontent.com/24643893/57822932-45386880-77c8-11e9-9981-e6c05b839c51.png)

Please fill in the bug report template:


## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by liangcd** [comment]
Which version of ShardingSphere did you use?       sharding-proxy-4.0.0-RC1

Which project did you use? Sharding-JDBC or Sharding-Proxy?    Sharding-Proxy

Expect behavior:
Sharding-proxy should be compatible with mysql 5.6 legacy timestamp field .

Actual behavior:
running sharding-proxy with  mysql 5.6 legacy timestamp field (value = '0000-00-00 00:00:00') got follow error.
 Error:
 Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp

Reason analyze
  Mysql 5.6 allows timestamp field  with default value '0000-00-00 00:00:00', and it seems the proxy can not convert value '0000-00-00 00:00:00' to a java Timestamp.

Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

CREATE TABLE `tb_user_info_0` (
  `USER_CODE` varchar(50) NOT NULL,
  `CREATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USER_NAME` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`USER_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tb_user_info_1` (
  `USER_CODE` varchar(50) NOT NULL,
  `CREATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USER_NAME` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`USER_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `tb_user_info_0` (`USER_CODE`, `CREATE_TIME`, `UPDATE_TIME`, `USER_NAME`)
VALUES ('0', '0000-00-00 00:00:00', '2019-05-16 15:11:02', 'Bob');

INSERT INTO `tb_user_info_1` (`USER_CODE`, `CREATE_TIME`, `UPDATE_TIME`, `USER_NAME`)
VALUES ('1', '0000-00-00 00:00:00', '2019-05-16 14:44:41', 'Alice');

# config-sharding-test.yaml
schemaName: test

dataSources:
  ds_0:
    url: jdbc:mysql://172.16.4.253:3306/test?serverTimezone=UTC&useSSL=false
    username: aaa
    password: bbb
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  tables:
    tb_user_info:
      actualDataNodes: ds_0.tb_user_info_${0..1}
      tableStrategy:
        inline:
          shardingColumn: USER_CODE
          algorithmExpression: tb_user_info_${Integer.parseInt(USER_CODE.substring(USER_CODE.length() - 1)) % 2}
      keyGenerator:
        type: SNOWFLAKE
        column: USER_CODE
  bindingTables:
    - tb_user_info
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:

SQL:
select * from tb_user_info;

**Comment by tuohai666** [comment]
How do you execute the SQL?

**Comment by liangcd** [comment]
I used a CLI to execute the SQL in the test.

mysql -u root -pPassword -h 172.16.0.171 -P3307
mysql> use test;
mysql> select * from tb_user_info;
ERROR: 
Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
mysql> 

<img width="809" alt="WechatIMG449" src="https://user-images.githubusercontent.com/2353395/57844900-7a15e100-7803-11e9-8a1e-fe355bb7be03.png">

**Comment by tuohai666** [comment]
Get it. This exception is thrown by JDBC. Sharding-Proxy use JDBC as a backend to access databases, so if JDBC throws an exception, Sharding-Proxy will transfer the exception transparently to client. 

There's a workaround to resolve this problem, in your case, add parameter:
url: jdbc:mysql://172.16.4.253:3306/test?serverTimezone=UTC&useSSL=false&**zeroDateTimeBehavior=convertToNull**
The **zeroDateTimeBehavior** parameter convert the '0000-00-00 00:00:00' to NULL.
