### ISSUE TITLE
too slow when application running,version:4.0.0-RC1

### ISSUE THREAD

**Issue by Li-Turing** [apache/incubator-shardingsphere#2394]
application run slowly when i use default-datasource-name

shardingsphere will load shardingContext and connect to db,why do this?

there is much tables and colums, when shardingsphere do it,it is slow

my configuration:
  check.table.matedata.enable:false

slow function:
  loadDefaultTables()

@SneakyThrows
    public Map<String, TableMetaData> load(final ShardingRule shardingRule) {
        Map<String, TableMetaData> result = new HashMap<>();
        result.putAll(loadShardingTables(shardingRule));
        result.putAll(loadDefaultTables(shardingRule));
        return result;
    }

this function  is slow

**Comment by Li-Turing** [comment]
@tristaZero

**Comment by tristaZero** [comment]
Hi, instead of  loading the metadata from all of sharding tables and checking them,
`check.table.matedata.enable:false` will make Sharding Sphere only load the meta data from one sharding table and all tables from default data source. Because we need the metadata of sharding table.
So it is not a bug, but an optimization item. Please refer to [#1951](https://github.com/apache/incubator-shardingsphere/issues/1951).
If you're interested in it, please try to do it.

**Comment by MidnightFiend** [comment]
with RC1 , i find it load all table in the pointed db, which is not configured in "logic-tables=user,order,...".

is there any way to optimize the problem?

**Comment by MidnightFiend** [comment]
i had try this way. it`s not work. still go to get all table column metadata.

    <sharding:data-source id="shardingDataSource">
        <sharding:props>
            <prop key="check.table.metadata.enabled">false</prop>
        </sharding:props>
    ...

**Comment by Fermiz** [comment]
@tristaZero as you said, Sharding Sphere only load the meta data from one sharding table and all tables from default data source

**Comment by wephone** [comment]
`check.table.matedata.enable:false` is just only for sharding tables，my default datasource contains too many tables,this tables doesnt need sharding, but `loadDefaultTables()` took me an hour to boot my project.
