### ISSUE TITLE
no table route info; nested exception is java.lang.IllegalStateException: no table route info

### ISSUE THREAD

**Issue by iamzxj** [apache/incubator-shardingsphere#2440]
I obviously added TableRuleConfiguration, but I still get an error.

![2019-05-24_102608](https://user-images.githubusercontent.com/11895528/58298531-6fb0a400-7e0e-11e9-8757-b0c809b8ff36.png)
![2019-05-24_102704](https://user-images.githubusercontent.com/11895528/58298563-8e169f80-7e0e-11e9-9085-15e01ffffe64.png)

**Comment by terrymanu** [comment]
The error message is not enough, can you provide more information, follow template below is a good idea:

  ## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by iamzxj** [comment]
Sharding-JDBC：4.0.0-RC1
2.0.3 version works fine, when I adapt to 4.0.0-RC1 error
![2019-05-24_111055](https://user-images.githubusercontent.com/11895528/58300335-af7a8a00-7e14-11e9-9dbc-c6ce85fe7cce.png)

**Comment by iamzxj** [comment]
My profile is as follows
![2019-05-24_111212](https://user-images.githubusercontent.com/11895528/58300421-f8cad980-7e14-11e9-8f34-25ecde01a6ed.png)

**Comment by terrymanu** [comment]
what is your SQL?

**Comment by iamzxj** [comment]
Hibernate: 
    select
        storage0_.id as id1_0_,
        storage0_.created_by as created_2_0_,
        storage0_.created_date as created_3_0_,
        storage0_.deleted_by as deleted_4_0_,
        storage0_.deleted_date as deleted_5_0_,
        storage0_.deleted_flag as deleted_6_0_,
        storage0_.last_modified_by as last_mod7_0_,
        storage0_.last_modified_date as last_mod8_0_,
        storage0_.db_id as db_id9_0_,
        storage0_.address as address10_0_,
        storage0_.backgroundpicpath as backgro11_0_,
        storage0_.description as descrip12_0_,
        storage0_.detector_no as detecto13_0_,
        storage0_.device_no as device_14_0_,
        storage0_.en_name as en_name15_0_,
        storage0_.height as height16_0_,
        storage0_.ispublic as ispubli17_0_,
        storage0_.name as name18_0_,
        storage0_.owner as owner19_0_,
        storage0_.picpath as picpath20_0_,
        storage0_.tel as tel21_0_,
        storage0_.width as width22_0_ 
    from
        sample_storage storage0_ 
    where
        storage0_.db_id=1 
        and storage0_.deleted_flag=1 
    order by
        storage0_.id desc limit ?

**Comment by terrymanu** [comment]
The configuration you provided is not ShardingSphere's configuration, what's it?
Can you provide ShardingSphere's configuration?

**Comment by iamzxj** [comment]
I just wrap it into the springboot2.X configuration file
![2019-05-24_112542](https://user-images.githubusercontent.com/11895528/58300823-baceb500-7e16-11e9-9c9f-ad413e264898.png)

**Comment by iamzxj** [comment]
When there are more than 100 data sources, the configuration file of ShardingSphere is very troublesome to configure, so it is packaged based on the springboot configuration file mechanism.

**Comment by terrymanu** [comment]
I suggest one issue just focus one problem.
I just want to know, can you provide ShardingSphere's configuration?  I don't know what is your sharding strategy.

**Comment by terrymanu** [comment]
It seems like you do some additional development for ShardingSphere, can you try to original ShardingSphere first?

**Comment by terrymanu** [comment]
I will close this issue soon if no response any more
