### ISSUE TITLE
How to set dynamic workerId

### ISSUE THREAD

**Issue by yy1193889747** [apache/incubator-shardingsphere#2454]
<bean:properties id="keyGeneratorProps">
        <prop key="worker.id">?</prop>
    </bean:properties>
    <sharding:key-generator id="xxKeyGenerator" type="SNOWFLAKE" column="id" props-ref="keyGeneratorProps"/>

**Comment by terrymanu** [comment]
Hi, your issue do not include any context, can you provide more necessary information follow by template blow?

## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by yy1193889747** [comment]
4.00-RC1 Sharding-JDBC， I want use distributed Primary Key, but when I deploy two services,duplicate primary occurs.So how to set dynamic workerId?

**Comment by tristaZero** [comment]
```
<sharding:key-generator id="keyGenerator" type="INCREMENT" column="order_id" props-ref="props" />
    
    <bean:properties id="props">
        <prop key="work.id">123</prop>
    </bean:properties>
```
Doesn't it work？
@yy1193889747

**Comment by yy1193889747** [comment]
it work,  I temporarily use the following method  ψ(*｀ー´)ψ
<bean:properties id="props">
        <prop key="worker.id">${random.int[0,1024]}</prop>
 </bean:properties>

**Comment by childewuque** [comment]
> it work, I temporarily use the following method ψ(*｀ー´)ψ
> 
> ```
> <bean:properties id="props">
>         <prop key="worker.id">${random.int[0,1024]}</prop>
>  </bean:properties>
> ```
Why is it wrong to use it like this in my case？

spring 4.3，Sharding-JDBC 4.00-RC2

Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'random.int[0,1024]' in value "${random.int[0,1024]}"
