### ISSUE TITLE
The problem that the value of the bit type cannot be returned correctly

### ISSUE THREAD

**Issue by cel105302** [apache/incubator-shardingsphere#2460]
I used shardingproxy to do the sharding, but there is a field of bit type. The value stored in this field is 1 regardless of the number of questions. Please ask how to solve this problem. Thank you.

**Comment by tuohai666** [comment]
Please fill in the bug report template.
BTW, I don't understand "The value stored in this field is 1 regardless of the number of questions. ". Can you put on some screenshot?


## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).
