### ISSUE TITLE
When useing C++ to connect sharding-proxy,i found a bug

### ISSUE THREAD

**Issue by tianyijushi** [apache/incubator-shardingsphere#2470]
![图片](https://user-images.githubusercontent.com/34736778/58614839-1f44b500-82ec-11e9-8738-36e0ecc919b7.png)
when using C++ to connect sharding-proxy(4.0.0-RC1),the schemaName is null ,then connect failed

**Comment by tianyijushi** [comment]
Hope for quick feedback. We're using it now. Thanks!

**Comment by terrymanu** [comment]
Hi, if you are urgency, we will do our best to try to find problem.
But for all previous issues you submitted, you cannot reply any more when we ask you to provide future informations, it is not a good way to participate the community. 
We need corporate each other, if you have question, we will try to resolve them, but we still need you feedback your further information and status of the issue too.  If your problem is resolved, please update your issue's status. 

By the way, can you register your company at https://github.com/apache/incubator-shardingsphere/issues/234 if your company is using ShardingSphere? more feedback will support the community more and more strong.

For this issue, please provide more information followed by template, I don't kwon your using version, database env, sharding rule configuration, exception stack trace etc..., we need more information to investigate it.

**Comment by tianyijushi** [comment]
the detail infomation is in the bug  #2471
