### ISSUE TITLE
the query results inlude milisecond data 

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#2512]
hello,
      when i query data by sharding-proxy, I got results which including milisecond follow the datetime, eg. "2019-04-28 18:37:59.0", why ? is there any way to configure the proxy to avoid this ?
![image](https://user-images.githubusercontent.com/48242833/58952283-d6966b80-87c5-11e9-8921-606f9e08fb9c.png)

thx

**Comment by tuohai666** [comment]
@Myshiner Please fill in the bug report template.

## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by Myshiner** [comment]
thx for ur reply, i use sharding-proxy, and it's v3.1.0.
i didn't use sharding rule but master-slave, the table structure is "CREATE TABLE `test_default_time` (
  `id` int(11) NOT NULL AUTO_INCREMENT comment 'primary key id',
  `uname` varchar(50) NOT NULL DEFAULT '' comment 'user name',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `age` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'age',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4",  the create_time result should be like '2019-04-29 17:02:04' but i got '2019-04-29 17:02:04.0', so i doubt that maybe i got wrong configuration. Any suggest ?

**Comment by Myshiner** [comment]
Thx, so i have to pull the git code again and then recompile it ?

**Comment by tuohai666** [comment]
Yes.
