### ISSUE TITLE
Memory leak caused by using druid connection pool

### ISSUE THREAD

**Issue by iamzxj** [apache/incubator-shardingsphere#2614]
![sharding连接池不释放问题](https://user-images.githubusercontent.com/11895528/60191642-4056e200-9867-11e9-8fdf-0201c8c73555.png)
![Uploading 2019-06-26_230738.png…]()

**Comment by iamzxj** [comment]
![2019-06-26_230738](https://user-images.githubusercontent.com/11895528/60225935-8c337680-98bb-11e9-9757-67f9cd50f3a6.png)

**Comment by terrymanu** [comment]
Can you fill necessary information follow the template below? 

 ## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere-example/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by iamzxj** [comment]
version ： 4.0.0-RC1
project  ：Sharding-JDBC
When I use the druid database connection pool, the database connection pool will run out. Use the druid to exclude the connection leak tool and find that there is a problem with this line of code.

**Comment by iamzxj** [comment]
![60191642-4056e200-9867-11e9-8fdf-0201c8c73555](https://user-images.githubusercontent.com/11895528/60311562-57dabb80-998a-11e9-9f9d-98553825957e.png)

**Comment by iamzxj** [comment]
Is there an example code that uses druid as a connection pool?

**Comment by KomachiSion** [comment]
@iamzxj can you provide full sharding configuration? 
If upload a example code which can reproduce this problem to GitHub will be best.

**Comment by KomachiSion** [comment]
No response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
