### ISSUE TITLE
Hello, insert data error

### ISSUE THREAD

**Issue by M-make** [apache/incubator-shardingsphere#2615]
![image](https://user-images.githubusercontent.com/35563513/60227720-eb48b980-98c2-11e9-83d8-e4f7ba6ae4be.png)
![image](https://user-images.githubusercontent.com/35563513/60227726-f00d6d80-98c2-11e9-81a0-bc72b9cce4e0.png)
![image](https://user-images.githubusercontent.com/35563513/60227750-04ea0100-98c3-11e9-9132-1ffbea66e650.png)

**Comment by 1397649957** [comment]
Jdbc driver can run normally

**Comment by 1397649957** [comment]
I set the shop_id as the primary key and it is automatically growing.

**Comment by terrymanu** [comment]
Can you fill necessary information follow the template below? 

 ## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere-example/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by terrymanu** [comment]
Another problem is could you rename the title of issue? it is too generic and not for search friendly.

**Comment by terrymanu** [comment]
duplicate with #2622
