### ISSUE TITLE
NullPointerException in ShardingRule class

### ISSUE THREAD

**Issue by F191919** [apache/incubator-shardingsphere#2662]
There are methods in the createBindingTableRules of the 82 lines in the ShardingRule class that use the broadcastTables property.
At this time, broadcastTables is empty, so it will report NullPointerException 
![image](https://user-images.githubusercontent.com/11403274/60712996-c00d3c80-9f4a-11e9-90c7-68cb4e2a2d6f.png)
![image](https://user-images.githubusercontent.com/11403274/60713049-e206bf00-9f4a-11e9-9016-1cc37b620c96.png)

**Comment by terrymanu** [comment]
Can you fill necessary information followed by template below?

**Comment by terrymanu** [comment]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere-example/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by F191919** [comment]
the version I used is 4.0.0-RC1 and the project is Sharding-JDBC . I think the reason is that no short judgment in the isBroadcastTable method in the ShardingRule class.

**Comment by terrymanu** [comment]
what's mean for `short judgment`?

**Comment by F191919** [comment]
null judgment

**Comment by KomachiSion** [comment]
@F191919 
broadcastTables has empty linked list as default value in ShardingRuleConfiguration.
I think there are some configuration mistakes in your sharding configuration.

Can you provide your sharding configuration?

**Comment by F191919** [comment]
Yes, there are some configuration mistakes in my sharding configuration. I have solved it. I think it is better to throw an exception hint here.
