### ISSUE TITLE
spring.shardingsphere.sharding.default-data-source-name is not configured in the data slice and read/write separation configuration of the springboot configuration in the user manual

### ISSUE THREAD

**Issue by F191919** [apache/incubator-shardingsphere#2685]
using:
Sharding-JDBC:4.0.0-RC1 
spring.shardingsphere.sharding.default-data-source-name is not configured in the data slice and read/write separation configuration of the springboot configuration in the user manual.

![image](https://user-images.githubusercontent.com/11403274/60896266-a21c4080-a298-11e9-869e-b9988e00beb3.png)

**Comment by KomachiSion** [comment]
@F191919, Excuse me, I didn't get what's your problem, can you describe with more detail by template.

**Comment by KomachiSion** [comment]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere-example/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by F191919** [comment]
In your official documentation(https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/configuration/config-spring-boot/), the data fragmentation + read-write separation configuration example does not set the value of default-data-source-name.

**Comment by KomachiSion** [comment]
This parameter is designed to be nullable, so the doc does not set the value.

**Comment by F191919** [comment]
However, if this value is not set in the project, it will  Caused by: java.lang.IllegalStateException: Missing the data source name: 'null'

**Comment by KomachiSion** [comment]
I strongly recommend you describe with more detail by template. It's hard to reproduce problem according to the information you provided now.
