### ISSUE TITLE
Table modification of sub-table data error reporting

### ISSUE THREAD

**Issue by wanggang931111** [apache/incubator-shardingsphere#2835]
Tables with separate tables to modify data errors，My approach uses a Distributed Annotation @TxcTransaction
![image](https://user-images.githubusercontent.com/51226924/62750068-53c5b180-ba91-11e9-98b5-79a503fa8794.png)

**Comment by terrymanu** [comment]
Bad SQL grammar, please check you SQL first

**Comment by wanggang931111** [comment]
> 错误的SQL语法，请先检查SQL
No problem with sql. I can put it directly into the library and execute it. Is there any configuration missing?

**Comment by terrymanu** [comment]
Can you fill necessary information? the template is below:

**Comment by terrymanu** [comment]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by terrymanu** [comment]
@wanggang931111 Can you explain the reason for issue closed?

**Comment by wanggang931111** [comment]
> @wanggang931111你能解释一下问题的原因吗？
It's the problem of distributed transaction in LCN, change this annotation it will be all right,but I don't know if it has compatibility with middleware.
![image](https://user-images.githubusercontent.com/51226924/62761065-37893b00-bab8-11e9-8259-c4789467f3b3.png)
