### ISSUE TITLE
The first time the sql is executed after the service starts, it is very slow. test on 4.0.0-RC1 and 4.0.0-RC2

### ISSUE THREAD

**Issue by philoli11** [apache/incubator-shardingsphere#2930]
This happens when 10 threads are concurrently tested.

**Comment by RaigorJiang** [comment]
How slow is it? Can you provide more information?

**Comment by philoli11** [comment]
> How slow is it? Can you provide more information?

1 second slower than version 3.1.0, tested with native jdbc, and I don't kown why . I monitor it with skywalking then I found the problem is in the parseSQL phase, but I didn't go to see the source code. Hope you can help me.

**Comment by terrymanu** [comment]
Because of ShardingSphere 4.x changed the SQL parse engine to support more SQL, but performance of parser is slow than before. After first time to parse, SQL AST will be cached.
I don't think this is a bug, it is necessary balance of design and performance.
By the way, even use old parse engine, the performance is faster than new parse engine, but still can not reach the benchmark of internet OLTP systems.
