### ISSUE TITLE
support query hint context for sharding-proxy

### ISSUE THREAD

**Issue by betterjava** [apache/incubator-shardingsphere#3057]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
No.
### Describe the feature you would like.
Support query hint context for sharding-proxy.It looks like that:

- sctl:hint show status
   result like that:

|master_only| database_only|database_sharding_values|table_sharding_values|
|---|---|---|---|
|0|1|value1,value2||
- sctl:hint show status table=user
   result like that:

|master_only|database_only|database_sharding_values|table_sharding_values|
|---|---|---|---|
|0|0|value1,value2|value3,value4|

Maybe the commands design is not clearly enough.We can discuss here.

**Comment by cherrylzhao** [comment]
this is my opinion

- sctl:hint show status
   result like that:

  | master_only | sharding_type   |
  |:------------|:----------------|
  |true / false   | databases_only / tables_only? / databases_tables|

- sctl:hint show table status
   result like that:

  | table_name | database_sharding_values | table_sharding_values |
  |:-----------|:-------------------------|:----------------------|
  |t_order     | value1,value2            | value1,value2         |

**Comment by betterjava** [comment]
Ok,I understood that.Two main differences between our opinions:
- the type of master_only is CHAR not BIT
- show table status command have no parameters,and will show all tables's status.

Agree with that.I will do this feature today.

**Comment by betterjava** [comment]
@cherrylzhao what 's  `tables_only` meaning in sharding_type?

**Comment by cherrylzhao** [comment]
>what 's tables_only meaning in sharding_type?I think databases_only and databases_tables is enough.

we have example to shard table only, so I'm doubting about whether it could be supported in hint, you can ignore it at first.

> thow to show database sharding values if database_only?

we can list all the logic tables if possible, or just list a wildcard of abbreviation.

**Comment by betterjava** [comment]
With the second question,I mean how to show database sharding values if database_only,because if the database_only,the `table_name` will be empty.

**Comment by cherrylzhao** [comment]
if table_name is empty, we can get all the logic table from ShardingRule if possible.

**Comment by betterjava** [comment]
I understand.

**Comment by Myshiner** [comment]
Seems that in sharding-proxy command-line, it doesnt support "sctl:hint show stauts", it threw errors:
mysql> sctl:hint show status;
ERROR 10002 (C1000): 2Unknown exception: [sctl:hint show status]

sharding-proxy version: 4.0.0-RC2

**Comment by betterjava** [comment]
@Myshiner This feature is planned to be added in version 4.0.0-RC3 and is still under development.

**Comment by Myshiner** [comment]
Great.Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [apache/incubator-shardingsphere] support query hint context for sharding-proxy (#3057)From: liya To: apache/incubator-shardingsphere CC: Myshiner ,Mention @Myshiner This feature is planned to be added in version 4.0.0-RC3 and is still under development.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apache/incubator-shardingsphere/issues/3057?email_source=notifications\u0026email_token=ALQCBEMG3ABJH4BGOFOSKVDQLNFHXA5CNFSM4IX5ARJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7RS5RI#issuecomment-534982341",
"url": "https://github.com/apache/incubator-shardingsphere/issues/3057?email_source=notifications\u0026email_token=ALQCBEMG3ABJH4BGOFOSKVDQLNFHXA5CNFSM4IX5ARJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7RS5RI#issuecomment-534982341",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
