### ISSUE TITLE
Performance tests data to the shadow table

### ISSUE THREAD

**Issue by chuchengyi** [apache/incubator-shardingsphere#3269]
Now，Performance testing in distributed systems is a regular process.
Performance tests will generate dirty data.Sharding-jdbc shuld write performance test data to the shadow table.
personally recommend considering providing plugins to support shadow tables in the sql execution layer.

**Comment by terrymanu** [comment]
It is a good idea, if somebody interesting and want to do this feature, we can talk about further.

**Comment by yanyzy** [comment]
We want to do this through SQL parse and add router, add a tag field in sql, and according to this field, route to shadow database.

Here is a simple design，and we chose the second way.  because ThreadLocal might introduce other problems.

![image](https://user-images.githubusercontent.com/30677017/70055785-3bb40800-1615-11ea-9d29-3255f1608174.png)

Comments or Suggestions on this design are welcome!

**Comment by terrymanu** [comment]
I like the SQL parser way, it can do with sharding-jdbc and sharding-proxy together. How do you think? @yanyzy

**Comment by yanyzy** [comment]
Yes, in this way, we only use SQL to judge whether route to the shadow database, and user just needs to write the SQL according to the rules. so both sharding-jdbc and sharding-proxy can implement it. @terrymanu
