### ISSUE TITLE
与MybatisPlus不兼容

### ISSUE THREAD

**Issue by xr2117** [apache/incubator-shardingsphere#3438]
org.apache.shardingsphere.core.optimize.sharding.segment.select.pagination.Pagination 

```java
    private int getValue(final PaginationValueSegment paginationValueSegment, final List<Object> parameters) {
        return paginationValueSegment instanceof ParameterMarkerPaginationValueSegment
                ? (int) parameters.get(((ParameterMarkerPaginationValueSegment) paginationValueSegment).getParameterIndex())
                : ((NumberLiteralPaginationValueSegment) paginationValueSegment).getValue();
    }
```

MybatisPlus 分页Page使用的long类型 ShardingJDBC 转换int 不兼容 出现转换异常

**Comment by RaigorJiang** [comment]
please fill in the issue template as follow. Thanks.

Bug Report
For English only, other languages will not accept.

Before report a bug, make sure you have:

Searched open and closed GitHub issues.
Read documentation: ShardingSphere Doc.
Please pay attention on issues you submitted, because we maybe need more details.
If no response more than 7 days and we cannot reproduce it on current information, we will close it.

Please answer these questions before submitting your issue. Thanks!

Which version of ShardingSphere did you use?
Which project did you use? Sharding-JDBC or Sharding-Proxy?
Expected behavior
Actual behavior
Reason analyze (If you can)
Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

**Comment by xr2117** [comment]
I am Chinese, English is not very good.



Sharding-jdbc JDBC latest version

Mybatisplus latest version



## problem

The page method of the mybatisplus Page object accepts an int parameter.
And sharding-jdbc receives the int type

In source
Package org.apache.shardingsphere.core.optimize.sharding.segment.select.pagination;
getValue method convert to int
Throw a conversion exception

## recurrent
Use the MybatisPlus Page object to page through the query to reproduce

## hope
Integrated mybatisplus compatible

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
