### ISSUE TITLE
A table without rules cannot get column information through "show full fields from table name"

### ISSUE THREAD

**Issue by waterMeteors** [apache/incubator-shardingsphere#3518]
when I use statements that is "show full fields from table name“.
if the table has rules , the result is column name of table.
if the table has not rules , the result is nothing.

accessory：
1. shardingsphere version is 4.0R2

**Comment by terrymanu** [comment]
Can you change the title as a whole sentence and to make it for search friendly?

**Comment by waterMeteors** [comment]
ok. the title has been modified.

**Comment by RaigorJiang** [comment]
Hi, @waterMeteors 
According to the existing logic, when the DAL statement (like show full fields, show create table) cannot find the routing rule, it uses random routing.  so that:
1,  if the routing database **has** the target table, we will get correct result;
2, if the routing database **doesn't have** the target table, we will get an error: 'table doesn't exist';

Did you configure the 'defaultDataSourceName'?     
If you can configure 'defaultDataSourceName', I think we can route to default data source in the case.
What do you think?

**Comment by waterMeteors** [comment]
Hi,RaigorJiang
I confirmed the sharding cinfiguration file, It is not configured the 'defaultDataSourceName'. I will try to add the it. Thank you!

**Comment by RaigorJiang** [comment]
@waterMeteors   Sorry, there is a misunderstanding,  if you configure 'defaultDataSourceName',  now the DAL statement will still route to a random data source. 
If you agree, we need to make some modifications to make it effective.

**Comment by waterMeteors** [comment]
@RaigorJiang When I was doing this,I create same table information in both databases. so random routing to any databases should have table information.I only read the source code of 3.*.*,and the understanding may be biased.I think you can try your method.Thank you very mach for you answer

**Comment by RaigorJiang** [comment]
@waterMeteors  Modified,  now you can try with the latest dev branch, thank you!
