### ISSUE TITLE
When i insert a new record , i meet a error "Caused by: java.sql.SQLException: Column count doesn't match value count at row 1"

### ISSUE THREAD

**Issue by ronyuzhang** [apache/incubator-shardingsphere#3531]
## Bug Report
i debug a  low layer code, i found “order_assisted”、“user_assisted” word in generated sql， but i did not add “order_assisted”、“user_assisted into my table，this cause “Column count doesn't match value count at row 1"。

**Comment by terrymanu** [comment]
Please fill necessary information follow the template below:

## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by ronyuzhang** [comment]
I found the cause of the problem ， sorry， i have  a mistake in property files.
