### ISSUE TITLE
sharding-proxy cannot query data  when 'max.connections.size.per.query=1' for server.yaml  using springboot and mybatis framework

### ISSUE THREAD

**Issue by geomonlin** [apache/incubator-shardingsphere#3725]
sharding-proxy version: dev,4.0.0-rc3

configuration：
       [config-sharding.yaml](https://github.com/apache/incubator-shardingsphere/blob/dev/sharding-proxy/sharding-proxy-bootstrap/src/main/resources/conf/config-sharding.yaml)
      [server.yaml](https://github.com/apache/incubator-shardingsphere/blob/dev/sharding-proxy/sharding-proxy-bootstrap/src/main/resources/conf/server.yaml)

[Running example](https://github.com/apache/incubator-shardingsphere-example/blob/dev/sharding-proxy-example/sharding-proxy-boot-mybatis-example/src/main/java/org/apache/shardingsphere/example/proxy/spring/boot/mybatis/SpringBootStarterExample.java)

**Comment by tuohai666** [comment]
This issue is caused by https://github.com/apache/incubator-shardingsphere/issues/3231.

max.connections.size.per.query=1 means Proxy will use MemoryQueryResult in this full routing case.

In MemoryQueryResult.java:

`return metaData.isSigned(columnIndex) ? resultSet.getInt(columnIndex) : resultSet.getLong(columnIndex);
`

This line will anyhow return a Long Object instead an Integer Object or a Long object. Proxy will burst an exception if the data type is inconsistent.
