### ISSUE TITLE
4.0.0 dosen't support LocalDateTime

### ISSUE THREAD

**Issue by shuohao** [apache/incubator-shardingsphere#3973]
![QQ截图20200114194609](https://user-images.githubusercontent.com/4637107/72341978-8cd01500-3706-11ea-9cb6-be4444056cb8.png)

befort 4.0.0 version like 4.0.0-RC3 it's worked well.

**Comment by tuohai666** [comment]
Hi @shuohao,

Thanks for your report. Can you answer these questions?

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by shaoyifan** [comment]
4.0.0 base on java 7， so can`t support LocalDateTime 😪

**Comment by dongzl** [comment]
Hi @shaoyifan , ShardingSphere work well on jdk 8, what's your problem.

**Comment by shaoyifan** [comment]
> Hi @shaoyifan , ShardingSphere can work well on jdk 8, what's your problem.

yes，it can works well ，but sometimes，our project some entity may use java.time.LocalDateTime instead of java.util.Date，but I found ShardingResultSet dont has any method to parse LocalDateTime ，because 4.0.0 base on java7。 LocalDateTime since 1.8

**Comment by dongzl** [comment]
oh yes, ShardingSphere will upgrade JDK's version in 5.x, #3097 .

**Comment by shaoyifan** [comment]
> oh yes, ShardingSphere will upgrade JDK's version in 5.x, #3097 .

When will 5. X be released？

**Comment by dongzl** [comment]
The 4.0.0 stable version was released just now, and 5.x is in development. 

There is no exact release time yet. You can stay focused on ShardingSphere community.

**Comment by kimmking** [comment]
@shuohao @shaoyifan  
Hi~
I think we can use util.Date instead of LocalDateTime class in your pojo, and conver it in your biz logic methods.
or ---
We also can use mybatis TypeHandler to process your specific type converted to another type.

**Comment by tuohai666** [comment]
The result need to be converted to LocalDateTime in QueryResult. 4.x do not support this yet since it's based on JDK 7. Let's wait for 5.x.
