### ISSUE TITLE
Not support JDBC getCatalog

### ISSUE THREAD

**Issue by shalousun** [apache/incubator-shardingsphere#4014]
sharding-jdbc: 4.0.0
```
@Resource
private DataSource shardingDataSource;

public String generateTableSchema(String tableName) {
        Connection connection = null;
        try {
            connection = shardingDataSource.getConnection();
            DatabaseMetaData meta = connection.getMetaData();
            ResultSet columns = meta.getColumns(connection.getCatalog(), "%", tableName, "%");
            while (columns.next()) {
                String columnName = columns.getString("COLUMN_NAME");
                String isAutoIncrement = columns.getString("IS_AUTOINCREMENT");
                int digits = columns.getInt("DECIMAL_DIGITS");
                int dataType = columns.getInt("DATA_TYPE");
                String remarks = columns.getString("REMARKS");
                String datatype = columns.getString("DATA_TYPE");
                String columnsize = columns.getString("COLUMN_SIZE");
                String decimaldigits = columns.getString("DECIMAL_DIGITS");
                String isNullable = columns.getString("IS_NULLABLE");
                //Printing results
                System.out.println(columnName + "---" + datatype + "---" + columnsize + "---" + decimaldigits + "---" + isNullable + "---" + isAutoIncrement);
            }

        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        return null;
}
```
exception:
```
Caused by: java.sql.SQLFeatureNotSupportedException: getCatalog
	at org.apache.shardingsphere.shardingjdbc.jdbc.unsupported.AbstractUnsupportedOperationConnection.getCatalog(AbstractUnsupportedOperationConnection.java:91)
```

**Comment by ssxlulu** [comment]
Yes, we haven't support the feature now.

**Comment by kimmking** [comment]
@shalousun  Actually, mysql&oracle doesn’t support catalog. 

In a abstract Database model, a db instance contains several catalogs, each catalog contains several schema, every schema have many tables/views and other objects.Then we used to use Database in a specified case instead of the two concepts: catalog&schema. In mysql jdbc driver, the method connection.getCatalog will return databaseName string.

We can use null or databaseName(mysql)/userName(oracle) instead of catalog in many methods like your above codes.

Further more, sharding jdbc/proxy can wrap and route a logic database to more than one database, so we can't decide which db name should be returned to caller. So, then you will know as a result, sharding jdbc/proxy can't support the feature till now.

**Comment by terrymanu** [comment]
We have no plan to do this.
I can label the requirement as volunteer wanted for several days.
If someone interesting about it, please reply here.

**Comment by kimmking** [comment]
Another method `getSchema()` is the same.

**Comment by zjcnb** [comment]
> We have no plan to do this.
> I can label the requirement as volunteer wanted for several days.
> If someone interesting about it, please reply here.

I am interested in

> We have no plan to do this.
> I can label the requirement as volunteer wanted for several days.
> If someone interesting about it, please reply here.

I am interested in

**Comment by kimmking** [comment]
> > We have no plan to do this.
> > I can label the requirement as volunteer wanted for several days.
> > If someone interesting about it, please reply here.
> 
> I am interested in

Logic schema can be as the result of getSchema()/getCatalog() method in mysql,
But pg&oracle, it's different.

**Comment by kimmking** [comment]
@zjcnb  Anything forward or problems ?

**Comment by terrymanu** [comment]
Maybe we should close this issue until other person interesting about this.
